name: build

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build-go:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - name: Build
        run: |
          go mod download
          go run cmd/download_ui/download_ui.go
          CGO_ENABLED=0 go build -o /tmp/cayley ./cmd/cayley
          go run github.com/gobuffalo/packr/v2/packr2
          git checkout -- ./packrd/dummy.go
          go get -u golang.org/x/lint/golint
          bash lint.sh
          go test -v ./...
