name: build

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build-go:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [1.13, 1.16]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - name: Build
        run: |
          go mod download
          go run cmd/download_ui/download_ui.go
          CGO_ENABLED=0 go build -o /tmp/cayley ./cmd/cayley
          go run github.com/gobuffalo/packr/v2/packr2
          git checkout -- ./packrd/dummy.go
          if [[ $GOVERSION =~ ^go1\.13 ]]; then
            go get -u golang.org/x/lint/golint && bash lint.sh
          else
            # run go vet for other go versions, but do not fail
            go vet ./... || true
          fi
          go test -v ./...
